
package com.assinador;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Arquivo", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://wcfassinanetsuporte.assina.net.br/Arquivo.svc?wsdl")
public class Arquivo
        extends Service {

    private final static URL ARQUIVO_WSDL_LOCATION;
    private final static WebServiceException ARQUIVO_EXCEPTION;
    private final static QName ARQUIVO_QNAME = new QName("http://tempuri.org/", "Arquivo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wcfassinanetsuporte.assina.net.br/Arquivo.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARQUIVO_WSDL_LOCATION = url;
        ARQUIVO_EXCEPTION = e;
    }

    public Arquivo() {
        super(__getWsdlLocation(), ARQUIVO_QNAME);
    }

    public Arquivo(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARQUIVO_QNAME, features);
    }

    public Arquivo(URL wsdlLocation) {
        super(wsdlLocation, ARQUIVO_QNAME);
    }

    public Arquivo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARQUIVO_QNAME, features);
    }

    public Arquivo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Arquivo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *         returns IArquivo
     */
    @WebEndpoint(name = "IArquivo")
    public IArquivo getIArquivo() {

        return super.getPort(new QName("http://tempuri.org/", "IArquivo"), IArquivo.class);
    }

    /**
     * 
     * @param features
     *                 A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *                 on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default
     *                 values.
     * @return
     *         returns IArquivo
     */
    @WebEndpoint(name = "IArquivo")
    public IArquivo getIArquivo(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "IArquivo"), IArquivo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARQUIVO_EXCEPTION != null) {
            throw ARQUIVO_EXCEPTION;
        }
        return ARQUIVO_WSDL_LOCATION;
    }

}
