
package com.assinador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IArquivo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
                ObjectFactory.class
})
public interface IArquivo {

        /**
         * 
         * @param senha
         * @param sFileName
         * @param cnpjcpfcedente
         * @param f
         * @param codassinaempresa
         * @param cnpjcpfresponsavel
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadCNAB", action = "http://tempuri.org/IArquivo/UploadCNAB")
        @WebResult(name = "UploadCNABResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadCNAB", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadCNAB")
        @ResponseWrapper(localName = "UploadCNABResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadCNABResponse")
        public String uploadCNAB(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CNPJCPFRESPONSAVEL", targetNamespace = "http://tempuri.org/") String cnpjcpfresponsavel,
                        @WebParam(name = "CNPJCPFCEDENTE", targetNamespace = "http://tempuri.org/") String cnpjcpfcedente,
                        @WebParam(name = "sFileName", targetNamespace = "http://tempuri.org/") String sFileName,
                        @WebParam(name = "f", targetNamespace = "http://tempuri.org/") byte[] f);

        /**
         * 
         * @param senha
         * @param sFileName
         * @param cnpjcpfcedente
         * @param f
         * @param codassinaempresa
         * @param cnpjcpfresponsavel
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadNFEINF", action = "http://tempuri.org/IArquivo/UploadNFEINF")
        @WebResult(name = "UploadNFEINFResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadNFEINF", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadNFEINF")
        @ResponseWrapper(localName = "UploadNFEINFResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadNFEINFResponse")
        public String uploadNFEINF(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CNPJCPFRESPONSAVEL", targetNamespace = "http://tempuri.org/") String cnpjcpfresponsavel,
                        @WebParam(name = "CNPJCPFCEDENTE", targetNamespace = "http://tempuri.org/") String cnpjcpfcedente,
                        @WebParam(name = "sFileName", targetNamespace = "http://tempuri.org/") String sFileName,
                        @WebParam(name = "f", targetNamespace = "http://tempuri.org/") byte[] f);

        /**
         * 
         * @param senha
         * @param codassinaempresa
         * @param chnfe
         * @return
         *         returns com.assinador.MemoryStream
         */
        @WebMethod(action = "http://tempuri.org/IArquivo/retornoNFEINF")
        @WebResult(name = "retornoNFEINFResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "retornoNFEINF", targetNamespace = "http://tempuri.org/", className = "com.assinador.RetornoNFEINF")
        @ResponseWrapper(localName = "retornoNFEINFResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.RetornoNFEINFResponse")
        public MemoryStream retornoNFEINF(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CHNFE", targetNamespace = "http://tempuri.org/") String chnfe);

        /**
         * 
         * @param senha
         * @param lote
         * @param codassinaempresa
         * @return
         *         returns com.assinador.MemoryStream
         */
        @WebMethod(action = "http://tempuri.org/IArquivo/retornoCNAB")
        @WebResult(name = "retornoCNABResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "retornoCNAB", targetNamespace = "http://tempuri.org/", className = "com.assinador.RetornoCNAB")
        @ResponseWrapper(localName = "retornoCNABResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.RetornoCNABResponse")
        public MemoryStream retornoCNAB(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "LOTE", targetNamespace = "http://tempuri.org/") String lote);

        /**
         * 
         * @param senha
         * @param sFileName
         * @param cnpjcpfcedente
         * @param f
         * @param codassinaempresa
         * @param cnpjcpfresponsavel
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadTermoAditivo", action = "http://tempuri.org/IArquivo/UploadTermoAditivo")
        @WebResult(name = "UploadTermoAditivoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadTermoAditivo", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadTermoAditivo")
        @ResponseWrapper(localName = "UploadTermoAditivoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadTermoAditivoResponse")
        public String uploadTermoAditivo(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CNPJCPFRESPONSAVEL", targetNamespace = "http://tempuri.org/") String cnpjcpfresponsavel,
                        @WebParam(name = "CNPJCPFCEDENTE", targetNamespace = "http://tempuri.org/") String cnpjcpfcedente,
                        @WebParam(name = "sFileName", targetNamespace = "http://tempuri.org/") String sFileName,
                        @WebParam(name = "f", targetNamespace = "http://tempuri.org/") byte[] f);

        /**
         * 
         * @param senha
         * @param sFileName
         * @param cnpjcpfcedente
         * @param f
         * @param codassinaempresa
         * @param cnpjcpfresponsavel
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadTermoAditivoContrato", action = "http://tempuri.org/IArquivo/UploadTermoAditivoContrato")
        @WebResult(name = "UploadTermoAditivoContratoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadTermoAditivoContrato", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadTermoAditivoContrato")
        @ResponseWrapper(localName = "UploadTermoAditivoContratoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadTermoAditivoContratoResponse")
        public String uploadTermoAditivoContrato(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CNPJCPFRESPONSAVEL", targetNamespace = "http://tempuri.org/") String cnpjcpfresponsavel,
                        @WebParam(name = "CNPJCPFCEDENTE", targetNamespace = "http://tempuri.org/") String cnpjcpfcedente,
                        @WebParam(name = "sFileName", targetNamespace = "http://tempuri.org/") String sFileName,
                        @WebParam(name = "f", targetNamespace = "http://tempuri.org/") byte[] f);

        /**
         * 
         * @param chave
         * @param codassinadocumentoresponsavel
         * @param documentobin
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "SetDocumento", action = "http://tempuri.org/IArquivo/SetDocumento")
        @WebResult(name = "SetDocumentoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "SetDocumento", targetNamespace = "http://tempuri.org/", className = "com.assinador.SetDocumento")
        @ResponseWrapper(localName = "SetDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.SetDocumentoResponse")
        public String setDocumento(
                        @WebParam(name = "CODASSINADOCUMENTORESPONSAVEL", targetNamespace = "http://tempuri.org/") Integer codassinadocumentoresponsavel,
                        @WebParam(name = "DOCUMENTOBIN", targetNamespace = "http://tempuri.org/") byte[] documentobin,
                        @WebParam(name = "CHAVE", targetNamespace = "http://tempuri.org/") String chave);

        /**
         * 
         * @param chave
         * @param codassinadocumentoresponsavel
         * @return
         *         returns byte[]
         */
        @WebMethod(operationName = "GetDocumento", action = "http://tempuri.org/IArquivo/GetDocumento")
        @WebResult(name = "GetDocumentoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "GetDocumento", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetDocumento")
        @ResponseWrapper(localName = "GetDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetDocumentoResponse")
        public byte[] getDocumento(
                        @WebParam(name = "CODASSINADOCUMENTORESPONSAVEL", targetNamespace = "http://tempuri.org/") Integer codassinadocumentoresponsavel,
                        @WebParam(name = "CHAVE", targetNamespace = "http://tempuri.org/") String chave);

        /**
         * 
         * @param senha
         * @param f
         * @param codassinaempresa
         * @param cnpjcpf
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadCadastro", action = "http://tempuri.org/IArquivo/UploadCadastro")
        @WebResult(name = "UploadCadastroResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadCadastro", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadCadastro")
        @ResponseWrapper(localName = "UploadCadastroResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadCadastroResponse")
        public String uploadCadastro(
                        @WebParam(name = "CODASSINAEMPRESA", targetNamespace = "http://tempuri.org/") Integer codassinaempresa,
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CNPJCPF", targetNamespace = "http://tempuri.org/") String cnpjcpf,
                        @WebParam(name = "f", targetNamespace = "http://tempuri.org/") byte[] f);

        /**
         * 
         * @param senha
         * @param codigo
         * @param chave
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "GetDocumentoAssinar", action = "http://tempuri.org/IArquivo/GetDocumentoAssinar")
        @WebResult(name = "GetDocumentoAssinarResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "GetDocumentoAssinar", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetDocumentoAssinar")
        @ResponseWrapper(localName = "GetDocumentoAssinarResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetDocumentoAssinarResponse")
        public String getDocumentoAssinar(
                        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/") String senha,
                        @WebParam(name = "CODIGO", targetNamespace = "http://tempuri.org/") Integer codigo,
                        @WebParam(name = "CHAVE", targetNamespace = "http://tempuri.org/") String chave);

        /**
         * 
         * @param descricao
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "GetComunicacao", action = "http://tempuri.org/IArquivo/GetComunicacao")
        @WebResult(name = "GetComunicacaoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "GetComunicacao", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetComunicacao")
        @ResponseWrapper(localName = "GetComunicacaoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetComunicacaoResponse")
        public String getComunicacao(
                        @WebParam(name = "DESCRICAO", targetNamespace = "http://tempuri.org/") String descricao);

        /**
         * 
         * @param requisicaoCertificado
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "UploadContratoNovo", action = "http://tempuri.org/IArquivo/UploadContratoNovo")
        @WebResult(name = "UploadContratoNovoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "UploadContratoNovo", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadContratoNovo")
        @ResponseWrapper(localName = "UploadContratoNovoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.UploadContratoNovoResponse")
        public String uploadContratoNovo(
                        @WebParam(name = "requisicaoCertificado", targetNamespace = "http://tempuri.org/") com.assinador.UploadContratoNovo.RequisicaoCertificado requisicaoCertificado);

        /**
         * 
         * @param codassinaresponsavel
         * @param resultado
         * @param chave
         * @return
         *         returns java.lang.String
         */
        @WebMethod(operationName = "GetTesteVersao", action = "http://tempuri.org/IArquivo/GetTesteVersao")
        @WebResult(name = "GetTesteVersaoResult", targetNamespace = "http://tempuri.org/")
        @RequestWrapper(localName = "GetTesteVersao", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetTesteVersao")
        @ResponseWrapper(localName = "GetTesteVersaoResponse", targetNamespace = "http://tempuri.org/", className = "com.assinador.GetTesteVersaoResponse")
        public String getTesteVersao(
                        @WebParam(name = "CODASSINARESPONSAVEL", targetNamespace = "http://tempuri.org/") Integer codassinaresponsavel,
                        @WebParam(name = "CHAVE", targetNamespace = "http://tempuri.org/") String chave,
                        @WebParam(name = "RESULTADO", targetNamespace = "http://tempuri.org/") String resultado);

}
